services:
  - type: web
    name: frontend
    env: static
    buildCommand: bun install && bun run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
